# Muesli Project
## Data Preparation

Brief exploration of the data
* the Excel file has 4 different tabs:
* Orders:
    * Index (not consistent)
    * Order ID (unique?)
    * Order Date (bad format)
    * Ship Mode (string)
    * Custimer ID
    * Customer Name (why in orders?) --> drop later
    * Origin chanel (string)
    * Country
    * City
    * State
    * Postal code --> shange to int, than to str
    * Region
    * Catefgory --> drop
    * Sub-Category --> drop
    * Product ID --> drop
    * Sales --> transform and drop
    * Quantity --> transform and drop
    * Discount --> drop
    * Profit --> transform and drop
* Campaign data
    * Order ID
    * Arrival Scan Date
    * Customer Name
* Order Process data
    * Row ID --> important for the merging with orders, don't drop
    * Order ID
    * Order Date
    * On Truck Scan Date
    * Ship Mode
* InternData Study
    * Order ID
    * Ready to Ship Date
    * Pick up Date

In [93]:
# import all the important libraries:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Order File

In [95]:
# save each tab as a data frame:
# orders:
df_orders = pd.read_excel('../data_raw_copy.xlsx',sheet_name = 'Orders', header = 1)
df_orders.head(2)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714

In [34]:
# save the file as .csv:
df_orders.to_csv('../data_csv/orders.csv',sep = ',', header = True, index = False)

In [96]:
df_orders.shape

(9994, 19)

In [97]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           9994 non-null   int64
 1   Order ID        9994 non-null   str
 2   Order Date      9994 non-null   datetime64[us]
 3   Ship Mode       9994 non-null   str
 4   Customer ID     9994 non-null   str
 5   Customer Name   9994 non-null   str
 6   Origin Channel  9994 non-null   str
 7   Country/Region  9994 non-null   str
 8   City            9994 non-null   str
 9   State           9994 non-null   str
 10  Postal Code     9983 non-null   float64
 11  Region          9994 non-null   str
 12  Category        9994 non-null   str
 13  Sub-Category    9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Sales           9994 non-null   float64
 16  Quantity        9994 non-null   int64
 17  Discount        9994 non-null   float64
 18  Profit          9994 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(2), str(12)
memory usage: 1.4 MB

### Campaign File

In [21]:
df_campaign = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'Campaign Data', header = 0)
df_campaign.head(2)

         Order ID Arrival Scan Date Customer Name
0  CA-2019-109666        2019-05-03  Kunst Miller
1  CA-2019-138933        2019-05-03   Jack Lebron

In [34]:
# save the file as .csv:
df_campaign.to_csv('./data_csv/campaign.csv',sep = ',', header = True, index = False)

In [22]:
df_campaign.shape

(333, 3)

In [23]:
df_campaign.info()

<class 'pandas.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           333 non-null    str
 1   Arrival Scan Date  333 non-null    datetime64[us]
 2   Customer Name      333 non-null    str
dtypes: datetime64[us](1), str(2)
memory usage: 7.9 KB

### Process File

In [24]:
df_process = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'Order Process Data', header = 0)
df_process.head(2)

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing

In [35]:
df_process.to_csv('./data_csv/process.csv',sep = ',', header = True, index = False)

In [27]:
df_process.shape

(5899, 5)

In [28]:
df_process.info()

<class 'pandas.DataFrame'>
RangeIndex: 5899 entries, 0 to 5898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              5899 non-null   int64
 1   Order ID            5899 non-null   str
 2   Order Date          5899 non-null   datetime64[us]
 3   On Truck Scan Date  5899 non-null   datetime64[us]
 4   Ship Mode           5899 non-null   str
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 230.6 KB

### Intern File

In [26]:
df_intern = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'InternData Study', header = 0)
df_intern.head(2)

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03

In [36]:
df_intern.to_csv('./data_csv/intern.csv',sep = ',', header = True, index = False)

In [29]:
df_intern.shape

(290, 3)

In [30]:
df_intern.info()

<class 'pandas.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            290 non-null    str
 1   Ready to Ship Date  290 non-null    datetime64[us]
 2   Pickup Date         290 non-null    datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 6.9 KB

### Cleaning the df_orders
1. Lower case the columns
2. Make proper format for colum names with '_'

In [98]:
df_orders.head(5)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0.0,6.1512

In [99]:
df_orders.columns = df_orders.columns.str.lower()
df_orders.columns = df_orders.columns.str.replace(' ','_')

In [100]:
df_orders.head()

,index,order_id,order_date,ship_mode,customer_id,customer_name,origin_channel,country/region,city,state,postal_code,region,category,sub-category,product_id,sales,quantity,discount,profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714
2,48,CA-2019-169194,2019-06-20,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45.00,3,0.0,4.9500
3,60,CA-2019-111682,2019-06-17,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180.0,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30.00,2,0.0,3.3000
4,63,CA-2018-135545,2018-11-24,Standard Class,KM-16720,Kunst Miller,Email,United States,Los Angeles,California,90004.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10004633,13.98,2,0.0,6.1512

In [101]:
df_orders.columns

Index(['index', 'order_id', 'order_date', 'ship_mode', 'customer_id',
       'customer_name', 'origin_channel', 'country/region', 'city', 'state',
       'postal_code', 'region', 'category', 'sub-category', 'product_id',
       'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

We can't drop column index but we need to rename it to row_id (because we have row_id in a differemt dataframe order process):

In [102]:
df_orders = df_orders.drop(columns = ['customer_name'])

In [103]:
# renaming:
df_orders.rename(columns={
    "index": "row_id"
}, inplace=True)

In [104]:
df_orders.columns

Index(['row_id', 'order_id', 'order_date', 'ship_mode', 'customer_id',
       'origin_channel', 'country/region', 'city', 'state', 'postal_code',
       'region', 'category', 'sub-category', 'product_id', 'sales', 'quantity',
       'discount', 'profit'],
      dtype='str')

In [41]:
df_orders.dtypes

row_id                     int64
order_id                     str
order_date        datetime64[us]
ship_mode                    str
customer_id                  str
origin_channel               str
country/region               str
city                         str
state                        str
postal_code              float64
region                       str
category                     str
sub-category                 str
product_id                   str
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
dtype: object

In [17]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   row_id          9994 non-null   int64
 1   order_id        9994 non-null   str
 2   order_date      9994 non-null   datetime64[us]
 3   ship_mode       9994 non-null   str
 4   customer_id     9994 non-null   str
 5   origin_channel  9994 non-null   str
 6   country/region  9994 non-null   str
 7   city            9994 non-null   str
 8   state           9994 non-null   str
 9   postal_code     9983 non-null   float64
 10  region          9994 non-null   str
 11  category        9994 non-null   str
 12  sub-category    9994 non-null   str
 13  product_id      9994 non-null   str
 14  sales           9994 non-null   float64
 15  quantity        9994 non-null   int64
 16  discount        9994 non-null   float64
 17  profit          9994 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(2), str(11)
memory usage: 1.4 MB

In [105]:
# change the index data type to string (because we don't want numerical operations on it):
df_orders['postal_code'] = df_orders['postal_code'].astype('Int64').astype('string')

In [19]:
# double-check the data types
df_orders.dtypes

row_id                     int64
order_id                     str
order_date        datetime64[us]
ship_mode                    str
customer_id                  str
origin_channel               str
country/region               str
city                         str
state                        str
postal_code               string
region                       str
category                     str
sub-category                 str
product_id                   str
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
dtype: object

### Orders "merge""
So, we decided that one order_id should stand for ONE order (and not for many rows like now). That's why we "collapsed" data together:
* we will keep sales (as a sum, one per order)
* we will also keepp amount of items per order (also through .transform() method)
* and the same for sales

We don't know yet if we will use this data or not but better to:
* have it in agregated version
* we will have unique order_id, which allows us to merge dataframes together with unique order_id

In [106]:
# transform data: take together total sales, total profit, product quantity
df_orders['total_sales'] = df_orders.groupby("order_id")["sales"].transform("sum")

In [107]:
# now profit:
df_orders['total_profit'] = df_orders.groupby("order_id")["profit"].transform("sum")

In [108]:
# now quantity of the priducts:
df_orders['total_items'] = df_orders.groupby("order_id")["quantity"].transform("sum")

In [109]:
df_orders.head(2)

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,country/region,city,state,postal_code,...,category,sub-category,product_id,sales,quantity,discount,profit,total_sales,total_profit,total_items
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Email,United States,Los Angeles,California,90049,...,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741,102.218,15.9965,5
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Sales,United States,Eagan,Minnesota,55122,...,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714,63.440,27.9776,4

In [25]:
df_orders.head(2)

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,country/region,city,state,postal_code,...,category,sub-category,product_id,sales,quantity,discount,profit,total_sales,total_profit,total_items
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Email,United States,Los Angeles,California,90049,...,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741,102.218,15.9965,5
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Sales,United States,Eagan,Minnesota,55122,...,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714,63.440,27.9776,4

In [110]:
# all country is United States --> we can drop the column
df_orders['country/region'].unique()

<StringArray>
['United States']
Length: 1, dtype: str

In [111]:
df_orders = df_orders.drop(columns = 'country/region')

In [112]:
df_orders.columns

Index(['row_id', 'order_id', 'order_date', 'ship_mode', 'customer_id',
       'origin_channel', 'city', 'state', 'postal_code', 'region', 'category',
       'sub-category', 'product_id', 'sales', 'quantity', 'discount', 'profit',
       'total_sales', 'total_profit', 'total_items'],
      dtype='str')

In [51]:
df_orders.to_csv('../data_csv/just_copy.csv')

# HERE SHOULD BE THE PART ABOUT MERGING WITH ORDER PROCESS!

In [113]:
df_process=pd.read_csv('../data_csv/process_clean.csv',index_col=False)

In [114]:
df_process.head(2)

,row_id,order_id,order_date,on_truck_scan_date,ship_mode,order_year,order_month,order_weekday,truck_year,truck_month,truck_weekday
0,3074,CA-2019-125206,2019-01-03,2019-01-07,Express,2019,1,3,2019,1,0
1,4919,CA-2019-160304,2019-01-02,2019-01-09,Standard Processing,2019,1,2,2019,1,2

In [115]:
# now we drop all the columns we don't need in the process file:
df_process_short = df_process.drop(columns = ['order_id', 'order_date','ship_mode','order_year','order_month','order_weekday'])

In [116]:
df_process_short.head()

   row_id on_truck_scan_date  truck_year  truck_month  truck_weekday
0    3074         2019-01-07        2019            1              0
1    4919         2019-01-09        2019            1              2
2    4920         2019-01-09        2019            1              2
3    8604         2019-01-09        2019            1              2
4    8605         2019-01-09        2019            1              2

## try with merge

In [117]:
df_orders_merged = df_orders.merge(df_process_short,how='outer', on='row_id')

In [118]:
df_orders_merged.head(3)

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,city,state,postal_code,region,...,quantity,discount,profit,total_sales,total_profit,total_items,on_truck_scan_date,truck_year,truck_month,truck_weekday
0,1,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,...,2,0.0,41.9136,993.90,261.4956,5,2019-11-13,2019.0,11.0,2.0
1,2,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,...,3,0.0,219.5820,993.90,261.4956,5,2019-11-13,2019.0,11.0,2.0
2,3,CA-2019-138688,2019-06-12,Second Class,DV-13045,Sales,Los Angeles,California,90036,West,...,2,0.0,6.8714,14.62,6.8714,2,2019-06-19,2019.0,6.0,2.0

In [76]:
# save the merged with process:
df_orders_merged.to_csv('../data_csv/orders_process.csv')

Check for duplicates and deal with them:

In [119]:
# check for duplicates: 
df_orders_merged[["order_id"]].duplicated().value_counts()

False    5009
True     4985
Name: count, dtype: int64

In [120]:
# the number of unique order id:
df_orders_merged[["order_id"]].nunique()

order_id    5009
dtype: int64

In [121]:
# the amount of duplicated order id:
df_orders_merged["order_id"].duplicated().sum()

np.int64(4985)

Creating a new (clean) dataframe with just unique order_id values:

In [122]:
df_unique_orders = df_orders_merged.drop_duplicates(subset="order_id", keep="first")

In [123]:
df_unique_orders.shape

(5009, 24)

In [124]:
df_unique_orders.head(3)

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,city,state,postal_code,region,...,quantity,discount,profit,total_sales,total_profit,total_items,on_truck_scan_date,truck_year,truck_month,truck_weekday
0,1,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,...,2,0.00,41.9136,993.9000,261.4956,5,2019-11-13,2019.0,11.0,2.0
2,3,CA-2019-138688,2019-06-12,Second Class,DV-13045,Sales,Los Angeles,California,90036,West,...,2,0.00,6.8714,14.6200,6.8714,2,2019-06-19,2019.0,6.0,2.0
3,4,US-2018-108966,2018-10-11,Standard Class,SO-20335,Email,Fort Lauderdale,Florida,33311,South,...,5,0.45,-383.0310,979.9455,-380.5146,7,NaN,NaN,NaN,NaN

Dropping the columns that do not help us to answer our research question:

In [125]:
# now we drop all the columns we don't need
df_unique_orders = df_unique_orders.drop(columns = ['category', 'sub-category','product_id','sales','quantity','discount','profit'])

In [126]:
df_unique_orders.head()

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,city,state,postal_code,region,total_sales,total_profit,total_items,on_truck_scan_date,truck_year,truck_month,truck_weekday
0,1,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,993.9000,261.4956,5,2019-11-13,2019.0,11.0,2.0
2,3,CA-2019-138688,2019-06-12,Second Class,DV-13045,Sales,Los Angeles,California,90036,West,14.6200,6.8714,2,2019-06-19,2019.0,6.0,2.0
3,4,US-2018-108966,2018-10-11,Standard Class,SO-20335,Email,Fort Lauderdale,Florida,33311,South,979.9455,-380.5146,7,NaN,NaN,NaN,NaN
5,6,CA-2017-115812,2017-06-09,Standard Class,BH-11710,Email,Los Angeles,California,90032,West,3714.3040,300.7687,38,NaN,NaN,NaN,NaN
12,13,CA-2020-114412,2020-04-15,Standard Class,AA-10480,Email,Concord,North Carolina,28027,South,15.5520,5.4432,3,2020-04-22,2020.0,4.0,2.0

Saving the file:

In [127]:
df_unique_orders.to_csv('../data_csv/orders_unique.csv')

In [128]:
df_unique_orders.head(3)

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,city,state,postal_code,region,total_sales,total_profit,total_items,on_truck_scan_date,truck_year,truck_month,truck_weekday
0,1,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,993.9000,261.4956,5,2019-11-13,2019.0,11.0,2.0
2,3,CA-2019-138688,2019-06-12,Second Class,DV-13045,Sales,Los Angeles,California,90036,West,14.6200,6.8714,2,2019-06-19,2019.0,6.0,2.0
3,4,US-2018-108966,2018-10-11,Standard Class,SO-20335,Email,Fort Lauderdale,Florida,33311,South,979.9455,-380.5146,7,NaN,NaN,NaN,NaN

### Date Formats and new columns
Since we have the research focused on delivery dates / truck arrivals / warehouse open days, we need to have distribution by day (of a week) and also -- just in case -- by month and year (to see if there are some seasonal changes):

In [129]:
# order date -> bring to several columns (year, month, day)
df_unique_orders["order_year"]=df_unique_orders["order_date"].dt.year
df_unique_orders["order_month"]=df_unique_orders["order_date"].dt.month
df_unique_orders["order_weekday"]=df_unique_orders["order_date"].dt.dayofweek

In [130]:
df_unique_orders.head(5)

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,city,state,postal_code,region,total_sales,total_profit,total_items,on_truck_scan_date,truck_year,truck_month,truck_weekday,order_year,order_month,order_weekday
0,1,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,993.9000,261.4956,5,2019-11-13,2019.0,11.0,2.0,2019,11,4
2,3,CA-2019-138688,2019-06-12,Second Class,DV-13045,Sales,Los Angeles,California,90036,West,14.6200,6.8714,2,2019-06-19,2019.0,6.0,2.0,2019,6,2
3,4,US-2018-108966,2018-10-11,Standard Class,SO-20335,Email,Fort Lauderdale,Florida,33311,South,979.9455,-380.5146,7,NaN,NaN,NaN,NaN,2018,10,3
5,6,CA-2017-115812,2017-06-09,Standard Class,BH-11710,Email,Los Angeles,California,90032,West,3714.3040,300.7687,38,NaN,NaN,NaN,NaN,2017,6,4
12,13,CA-2020-114412,2020-04-15,Standard Class,AA-10480,Email,Concord,North Carolina,28027,South,15.5520,5.4432,3,2020-04-22,2020.0,4.0,2.0,2020,4,2

In [131]:
df_unique_orders.to_csv('../data_csv/orders_unique.csv')

In [132]:
df_unique_orders.head()

,row_id,order_id,order_date,ship_mode,customer_id,origin_channel,city,state,postal_code,region,total_sales,total_profit,total_items,on_truck_scan_date,truck_year,truck_month,truck_weekday,order_year,order_month,order_weekday
0,1,CA-2019-152156,2019-11-08,Second Class,CG-12520,Email,Henderson,Kentucky,42420,South,993.9000,261.4956,5,2019-11-13,2019.0,11.0,2.0,2019,11,4
2,3,CA-2019-138688,2019-06-12,Second Class,DV-13045,Sales,Los Angeles,California,90036,West,14.6200,6.8714,2,2019-06-19,2019.0,6.0,2.0,2019,6,2
3,4,US-2018-108966,2018-10-11,Standard Class,SO-20335,Email,Fort Lauderdale,Florida,33311,South,979.9455,-380.5146,7,NaN,NaN,NaN,NaN,2018,10,3
5,6,CA-2017-115812,2017-06-09,Standard Class,BH-11710,Email,Los Angeles,California,90032,West,3714.3040,300.7687,38,NaN,NaN,NaN,NaN,2017,6,4
12,13,CA-2020-114412,2020-04-15,Standard Class,AA-10480,Email,Concord,North Carolina,28027,South,15.5520,5.4432,3,2020-04-22,2020.0,4.0,2.0,2020,4,2

See the work on Interns File in the next Jupyter Notebook.